# Generated by Django 5.0 on 2024-01-13 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('excerpt', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('time_posted', models.DateField()),
                ('tag', models.CharField(choices=[('Featured', 'Featured'), ('New', 'New'), ('Best Selling', 'Best Selling')], max_length=12)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.author')),
            ],
        ),
    ]
