# Generated by Django 5.0 on 2024-01-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(null=True, to='blogpost.tag'),
        ),
    ]
