# Generated by Django 5.0 on 2024-01-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_rename_book_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='blogpost.tag'),
        ),
    ]
